#!/bin/bash
export ORACLE_SID=vtevidb1
export ORACLE_HOME=/u01/app/oracle/product/19.0.0.0/dbhome_1
export PATH=$ORACLE_HOME/bin:$PATH
export NLS_DATE_FORMAT="YYYY-MM-DD HH24:MI:SS"

DATETIME=$(date +"%Y%m%d_%H%M")
SECONDS=0

BKBASE="/u01/backup"
BKDIR="$BKBASE/BK_DB_LV0_$DATETIME"
BKLOG="$BKBASE/Log_BK"

mkdir -p "$BKDIR"
mkdir -p "$BKLOG"

LOGFILE="$BKLOG/LogBK_DB_LV1_$DATETIME.log"

echo "--- Start Backup: $(date) ---" >> "$LOGFILE"

$ORACLE_HOME/bin/rman TARGET / >> "$LOGFILE" 2>&1 <<EOF
RUN {
    CROSSCHECK BACKUP;
    CROSSCHECK ARCHIVELOG ALL;
    DELETE NOPROMPT EXPIRED BACKUP;
    DELETE NOPROMPT EXPIRED ARCHIVELOG ALL;
    DELETE NOPROMPT OBSOLETE;

    ALLOCATE CHANNEL d1 DEVICE TYPE DISK;
    ALLOCATE CHANNEL d2 DEVICE TYPE DISK;
    ALLOCATE CHANNEL d3 DEVICE TYPE DISK;
    ALLOCATE CHANNEL d4 DEVICE TYPE DISK;

    BACKUP AS COMPRESSED BACKUPSET INCREMENTAL LEVEL 1 DATABASE FORMAT '$BKDIR/datafile_LV1_%d_%T_%U.bkp' TAG='DB_LV1_$DATETIME';
    sql 'alter system archive log current'; --> Bỏ dòng này khi backup trên Standby database
    BACKUP AS COMPRESSED BACKUPSET ARCHIVELOG ALL FORMAT '$BKDIR/arch_LV1_%d_%T_%U.bkp' TAG='ARC_LV1_$DATETIME';
    BACKUP SPFILE FORMAT '$BKDIR/spfile_LV1_%d_%T_%U.bkp' TAG='SPFILE_LV1_$DATETIME';
    BACKUP CURRENT CONTROLFILE FORMAT '$BKDIR/controlfile_LV1_%d_%T_%U.bkp' TAG='CTL_LV1_$DATETIME';

    RELEASE CHANNEL d1;
    RELEASE CHANNEL d2;
    RELEASE CHANNEL d3;
    RELEASE CHANNEL d4;
}
EXIT;
EOF

echo "--- RMAN completed: $(date) ---" >> "$LOGFILE"

find "$BKBASE" -type d -empty -delete 2>/dev/null

echo "--- Cleaning up backup logs older than 15 days ---" >> "$LOGFILE"
find "$BKLOG" -type f -name "LogBK_DB_LV1_*.log" -mtime +15 -exec rm -f {} \;

DURATION=$SECONDS
HOURS=$((DURATION / 3600))
MINUTES=$(( (DURATION % 3600) / 60 ))
SECS=$((DURATION % 60))

echo "--- End Backup: $(date) ---" >> "$LOGFILE"
printf -- "--- Total Execution Time: %02d hours %02d minutes %02d secs ---\n" \
    "$HOURS" "$MINUTES" "$SECS" >> "$LOGFILE"
